# To update this file with your personal settings, please duplicate this file
# and name it 'config.yml'. This way your personal tokens will be safe.
# Store the config.yml file in the root of the directory (pyetm/config.yml).

# Paste your personal ETM API Token in this field. Never push this to GitHub!
# will be overridden by $ETM_API_TOKEN if you set that in env.
# The same token will work for beta and pro environments, but if you are interacting with beta or local,
# you will need the correct token for that environment.
# For more information, see: https://docs.energytransitionmodel.com/api/authentication#tokens-are-environment-specific
#
etm_api_token: your.token.here

# Override the API base URL - here you can set which environment of the ETM you want to interact with.
# Options include the default (pro), https://2025-01.engine.energytransitionmodel.com/api/v3 (a stable version) or
# https://beta.engine.energytransitionmodel.com/api/v3	(the staging environment), or http://localhost:3000/api/v3
# (your local environment).
# For more information, see: https://docs.energytransitionmodel.com/api/intro#environments
#
BASE_URL: https://engine.energytransitionmodel.com/api/v3

#TODO: Setup so the below is actually used
# URLs of your proxy server addresses (replace the examples below by your own settings)
# Never push authenticated servers (including user name and password) to Github!
proxy_servers:
  # http: http://user:pass@proxy.sample.com:8080
  # https: http://user:pass@secureproxy.sample.com:8080

# The separator your CSV files are using. The default is ',', but many European computers
# export CSV with a ';' as separator from Excel instead.
csv_separator: ','

# The decimal separator your CSV files are using. The default is '.', but depending on the
# national conventions, comma could be used as a decimal seperator instead.
decimal_seperator: '.'
